apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    {{- include "greeting-app-chart.backendLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "greeting-app-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "greeting-app-chart.backendLabels" . | nindent 8 }}
    spec:
      containers:
        - name: "{{ .Values.deployment.name }}container"
          image: "{{ .Values.deployment.image.app }}:{{ .Values.deployment.image.version }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP