deployment:
  name: helmworkshopdeployment
  replicaCount: 1
  image:
    app: helm-workshop
    version: 1.0-SNAPSHOT
    pullPolicy: IfNotPresent

service:
  name: helmworkshopservice
  type: NodePort
  port: 8081
  targetPort: 8080
  nodePort: 31234

appConfig:
  appName: helmworkshop